# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: William Gautreaux
title: Junior Software Engineer
email: gautreauxwill@gmail.com
website: https://runninoutoftime.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  runninoutoftime
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: will-gautreaux
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/will.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hey!
  I'm Will and I'm a senior computer science student at The University of Georgia. I've worked on many projects throughout my time at university and have developed teamwork and communication
  skills thanks to these projects. I currently have accepted a job as a Software Engineer, but am always looking for new opportunities to learn and grow as a developer.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Neural Networks vs Evolutionary Algorithms - Which clears Super Mario World first?
        link: github.com/Runninoutoftime/Mario-Speedrun-with-Evolutionary-Computation
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: https://github.com/Runninoutoftime/Mario-Speedrun-with-Evolutionary-Computation
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          This was a group project for my Evolutionary Computation class. We wanted to compare the algorithmic performance of neural networks and evolutionary algorithms compared to human players in Super Mario Bros. We learned a lot in regards to python and machine learning.
          Here's a short video too!
          <iframe width="560" height="315" src="https://www.youtube.com/embed/hLj-fChO6UQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
      - layout: top-middle
        title: Style Sensei
        link: github.com/Runninoutoftime/UGAHacks
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: https://github.com/Runninoutoftime/UGAHacks
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          I created this project for a hackathon. It was conceptualized and created in less than 48 hours, programmed entirely by me while a UI mockup was made by a friend.
        description: | # this will include new lines to allow paragraphs
          This project uses a combination of computer vision libraries and pre-trained models in a custom algorithm to determine the best outfit for the user. It was created as a way to learn more about computer vision and machine learning.
      - layout: top-middle
        title: Predicting Community Health Outcomes with Local Streetview Imagery
        link: github.com/Runninoutoftime/StreetviewHealthOutcomes
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: https://github.com/Runninoutoftime/StreetviewHealthOutcomes
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Many communities suffer from a lack of health data. This project aims to fix this.
        description: | # this will include new lines to allow paragraphs
          What happens when you combine streetview imagery with health data (like obesity rate, life expectancy, etc.) and machine learning? Well, the hope is we can predict accurate health information for communities that lack the proper information.
          This project is still in progress, but we hope to have it finished by this July in time for (****) conference.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: NCR Corporation
        link: ncr.com
        # link_text: boringcompany.com
        sub_title: Software Engineer Intern
        caption: May 2022 - Dec 2022
        description: | # this will include new lines to allow paragraphs
          At my time as an intern in NCR, I developed solutions for handling the large amounts of data that NCR works with. I also came in 2nd in the company wide global hackathon!
      - layout: left
        title: University of Georgia - THINC Lab
        link: http://thinc.cs.uga.edu
        # link_text: boringcompany.com
        sub_title: Undergraduate Researcher
        caption: Jan 2022 - May 2022
        description: | # this will include new lines to allow paragraphs
            Farming in Georgia is a labor intensive process. As part of my undergraduate studies, I worked in a lab on campus to develop a system that automatically sorts foods by their ripeness. This system uses a combination of computer vision and machine learning to determine the ripeness of a food and then connects to a robotic arm to sort the food.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Georgia
        caption: 2019 - 2023
        sub_title: BSc Computer Science
        description: | # this will include new lines to allow paragraphs
          Clubs and Awards:
          - Dean's List
          - UGA Associate of Computing Machinery Club Member
          - UGAHacks 7 winner
          - Humans vs Zombies Club Member
          - UGA Speed Networking Club Secretary

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Although I love working with computers, I have several other hobbies I enjoy doing!
      - Rock climbing
      - Raquetball
      - Gaming
      - Reading Sci-Fi (I know, I'm a nerd)
      - Playing with my dog


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
